### ISSUE TITLE
Installation error: most likely a problem with the leveldown package

### ISSUE THREAD

**Issue by rvennam** [ActiveState/cf-services-connector-nodejs#9]
npm install cf-services-connector fails.

```
npm WARN package.json brokertest@1.0.0 No description
npm WARN package.json brokertest@1.0.0 No repository field.
npm WARN package.json brokertest@1.0.0 No README data

> dtrace-provider@0.3.2 install /Users/rvennam/sandbox/brokertest/node_modules/cf-services-connector/node_modules/restify/node_modules/dtrace-provider
> node scripts/install.js

---------------
Building dtrace-provider failed with exit code 1 and signal 0
re-run install with environment variable V set to see the build output
---------------

> dtrace-provider@0.6.0 install /Users/rvennam/sandbox/brokertest/node_modules/cf-services-connector/node_modules/restify/node_modules/bunyan/node_modules/dtrace-provider
> node scripts/install.js


> leveldown@0.9.2 install /Users/rvennam/sandbox/brokertest/node_modules/cf-services-connector/node_modules/level/node_modules/leveldown
> node-gyp rebuild

...
 CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.0/snappy-stubs-internal.o
  CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.0/snappy.o
  LIBTOOL-STATIC Release/snappy.a
  CXX(target) Release/obj.target/leveldown/src/batch.o
In file included from ../src/batch.cc:5:
../node_modules/nan/nan.h:261:12: error: no member named 'New' in 'v8::String'
   return  _NAN_ERROR(v8::Exception::Error, errmsg);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:252:21: note: expanded from macro '_NAN_ERROR'
    fun(v8::String::New(errmsg))
        ~~~~~~~~~~~~^

...
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/rvennam/sandbox/brokertest/node_modules/cf-services-connector/node_modules/level/node_modules/leveldown
gyp ERR! node -v v4.2.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "cf-services-connector" "--save"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE

npm ERR! leveldown@0.9.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the leveldown@0.9.2 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the leveldown package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls leveldown
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/rvennam/sandbox/brokertest/npm-debug.log

```

**Comment by pswamikr** [comment]
I'm getting the same error , updated node to latest version , still get the same error

**Comment by jvenky68** [comment]
i get the same error event now. What is the recommended work arround or solution?

**Comment by rvennam** [comment]
See my PR https://github.com/hpcloud/cf-services-connector-nodejs/pull/10

**Comment by edsenabr** [comment]
.. is this project abandoned ? I see that your pull request, @rvennam, is pending for months. @shsu or @jdpaton , could you please take a look on this ?! BTW, that commit is already outdated, since level is already @ version 1.5.0 now.
